name: 'Testing embedded system - wokwi'
desciption: 'Wokwi test for insper embedded system course'
author: 'rafaelcorsi'

inputs:
  test_name:
    description: 'Test name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"

      - name: Install python
        run: |
          python -m pip install --upgrade pip
          pip install pytest toml

      - name: Install wokwi-cli
        run: |
          wget -q -O /usr/local/bin/wokwi-cli https://github.com/rafaelcorsi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x /usr/local/bin/wokwi-cli

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: build

      - name: Run test
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run:
          pytest test.py -ks exe1

      - name: Run test
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}

        run: |
          pytest test.py -ks "${{ inputs.test_name }}"
