name: 'Testing embedded system - wokwi'
desciption: 'Wokwi test for insper embedded system course'
author: 'rafaelcorsi'

inputs:
  token:
    description: 'Wokiwi token'
    required: true

  test_name:
    description: 'Test name'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
      with:
        python-version: "3.8"

    - name: Install python
      shell: bash
      run: |
          python -m pip install --upgrade pip
          pip install pytest toml

    - name: Install wokwi-cli
      shell: bash
      run: |
        wget -q -O /usr/local/bin/wokwi-cli https://github.com/rafaelcorsi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
        chmod +x /usr/local/bin/wokwi-cli

    - name: Run test
      shell: bash
      env:
        WOKWI_CLI_TOKEN: ${{ inputs.token}}
      run: |
        pytest /home/runner/work/_actions/insper-embarcados/actions-wokwi-test/v2/test.py -s --name "${{ inputs.test_name }}"
